<link rel="stylesheet" type="text/css" href="/css/gamming.css?v=0" />

<div id="fibbage_game">
	<div id="game_container">
		<div id="read_game" class="screen_game">
			<div id="read_player">
				<span class="player"></span><br> lee cuidadosamente la siguiente pregunta:
			</div>
			<div id="read_question">
				
			</div>
			<button id="read_btn" class="btn">Siguiente</button>
		</div>
		<div id="answer_game" class="screen_game">
			<div id="answer_players">
				<span id="answer_player" class="player"></span><br> dale una respuesta confusa a 
				<span id="answer_playerturn"></span>
			</div>
			<div id="answer_input">
				<input type="password" value="" style="color:#000">
			</div>
			<div id="answer_button"></div>
		</div>
		<div id="choose_game" class="screen_game">
			<div id="choose_title" style="font-size: 30px;">Elige la respuesta correcta</div>
			<div id="answers2choose">
				
			</div>

		</div>
		<div id="show_game" class="screen_game">
			<div id="correct_answer">
				La respuesta correcta es: <span></span>
			</div>
			<div id="player_win" class="player">
				El jugador <span></span> 
			</div>
			<div id="show_btn">
				<button id="show_next" class="btn">Siguiente</button>
			</div>
		</div>
		<div id="result_game" class="screen_game"></div>
	</div>
	<div id="fibbage_score">
		<input type="hidden" value="" id="question2">
	</div>
</div>
<script type="text/javascript" src="/js/websocket.js"></script>
<script type="text/javascript" src="/js/fibbage.js"></script>

