<div id="fibbage_game">
	<div id="read_game" class="screen_game">
		<div id="read_player">
			<span></span> lee cuidadosamente la siguiente pregunta:
		</div>
		<div id="read_question">
			
		</div>
		<button id="read_btn">Siguiente</button>
	</div>
	<div id="answer_game" class="screen_game">
		<div id="answer_player">
			<span id="answer_player"></span> dale una respuesta confusa a 
			<span id="answer_playerturn"></span>
		</div>
		<div id="answer_input">
			<input type="password" value="">
		</div>
		<button id="answer_btn">Siguiente</button>
	</div>
	<div id="choose_game" class="screen_game"></div>
	<div id="show_game" class="screen_game"></div>
	<div id="result_game" class="screen_game"></div>
</div>

<script type="text/javascript" src="/js/jquery.fibbage.js"></script>
<script type="text/javascript">
	<!--
	$(document).ready(function(){
		$("#fibbage_game").fibbage({
			"questions":<?php echo json_encode($questions)?>,
			"players":<?php echo json_encode($players)?>
		});
	});
	-->
</script>