<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php echo $title; ?></title>
		<link rel="stylesheet" type="text/css" href="/css/default.css?v=1.0" />
		<link rel="stylesheet" type="text/css" href="/css/header.css?v=1.0" />
		<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css?v=1.0" />
		<script type="text/javascript" src="/js/jquery-2.1.3.min.js?v=1.0"></script>
		<!--<script type="text/javascript" src="/js/jquery-ui.min.js?v=1.0"></script>-->
		<script type="text/javascript" src="/js/bootstrap.min.js?v=1.0"></script>
	</head>